version: '3.8'

services:
  nest-app:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:hacxk@postgres:5432/whatsapp_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hacxk
      POSTGRES_DB: whatsapp_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  postgres-data:
